version: "3"
services:
  arena_hicourt:
    image: registry.myarena7.com/arena/hicourt:${CI_COMMIT_REF_NAME}
    container_name: arena_hicourt
    networks:
      - micro_net
    environment:
      HICOURT_CONSUL_ADDR: "consul-dev:8500"
      MICRO_AUTH_ID: "admin"
      MICRO_AUTH_SECRET: "micro"
      MICRO_NETWORK_ADDRESS: "micro:8085"
      MICRO_RUNTIME_ADDRESS: "micro:8088"
      MICRO_REGISTRY_ADDRESS: "micro:8000"
      MICRO_CONFIG_ADDRESS: "micro:8001"
      MICRO_STORE_ADDRESS: "micro:8002"
      MICRO_BROKER_ADDRESS: "micro:8003"
      MICRO_ROUTER_ADDRESS: "micro:8084"
      MICRO_AUTH_ADDRESS: "micro:8010"
      MICRO_PROXY_ADDRESS: "micro:8081"
      MICRO_API_ADDRESS: "micro:8080"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: ${DOCKER_GELF_ADDRESS}
#        tag: "arena_hicourt"

networks:
  micro_net:
    external:
      name: "micro_net"
